version: '3.8'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword

networks:
  default:
    name: thinkphp-net
    driver: bridge
