<?php

namespace app\api\controller;


use app\common\library\Createlog;
use app\common\library\KsAgent;
use app\common\library\Otherapi;
use app\common\library\SmsNotice;
use app\common\model\Porder;
use Payapi\Jindjuhe;
use Payapi\Leshua;
use think\Log;
use think\Request;
use Util\Pinyin;

class Abin extends \app\common\controller\Base
{
    /**
     * @var \Recharge\Abin
     */
    public $service;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->service = new \Recharge\Abin();
    }

    public function recharge(Request $request){
        $param = $request->param();
        $resp = $this->service->recharge($param['out_trade_num'], $param['price'], $param['mobile'], $param['isp']);
        return djson(0, 'ok', $resp);
    }
    public function check(Request $request){
        $param = $request->param();
        $resp = $this->service->check($param['out_trade_num']);
        return djson(0, 'ok', $resp);
    }
    public function balance(){
        $resp = $this->service->balance();
        return djson(0, 'ok', $resp);
    }
}
