server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  user: root
  password: ''
  dbname: recharge-new

jwt:
  secret: recharge-new
  expire: 24 # hours

log:
  level: debug
  filename: logs/app.log
  max_size: 100
  max_backups: 10
  max_age: 30 