server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  user: root
  password: ''
  dbname: recharge-new

jwt:
  secret: recharge-new
  expire: 24 # hours
  refresh_secret: recharge-new-refresh
  refresh_expire: 168 # hours (7 days)

log:
  level: debug
  filename: logs/app.log
  max_size: 100
  max_backups: 10
  max_age: 30

redis:
  host: localhost
  port: 6380
  password: ""
  db: 0 